src/objects/System_Log__c.object
<CustomObject>
    <description>System log records created from Salesforce processes.</description>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Method__c</fullName>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <description>The name of the flow from which the log event was generated.</description>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Stage__c</fullName>
        <label>Flow Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <description>The severity of the log message.</description>
        <inlineHelpText>The severity of the log message.</inlineHelpText>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warn</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logged_From__c</fullName>
        <description>What type of process logged this event?</description>
        <inlineHelpText>What type of process logged this event?</inlineHelpText>
        <label>Logged From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Pentaho</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Script</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The reported log message.</description>
        <inlineHelpText>The reported log message.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Object_Id__c</fullName>
        <description>The Id of the related Object for which the log message was generated.</description>
        <inlineHelpText>The Id of the related Object for which the log message was generated.</inlineHelpText>
        <label>Related Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_UserName__c</fullName>
        <description>The UserName (login name) of the running user when the log was generated.</description>
        <inlineHelpText>The UserName (login name) of the running user when the log was generated.</inlineHelpText>
        <label>Running UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User executing the process from which the log event was generated.</description>
        <inlineHelpText>The User executing the process from which the log event was generated.</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>System_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The stack trace when the log was generated.</description>
        <inlineHelpText>The stack trace when the log was generated.</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <label>System  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <recordTypes>
        <fullName>Apex</fullName>
        <active>true</active>
        <label>Apex</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flow</fullName>
        <active>true</active>
        <label>Flow</label>
    </recordTypes>
    <recordTypes>
        <fullName>Script</fullName>
        <active>true</active>
        <label>Script</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Log_Event__e.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Method__c</fullName>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Log_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flow Log Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Stage__c</fullName>
        <label>Flow Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Object_Id__c</fullName>
        <label>Related Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_UserName__c</fullName>
        <label>Running UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Log Event</label>
    <pluralLabel>System Log Events</pluralLabel>
</CustomObject>

src/objects/System_Logger_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>On_Debug__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Debug</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                    <default>true</default>
                    <label>Debug Log</label>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Error__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Error</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Info__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Info</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Warn__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Warn</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <defaultValue>&quot;DEFAULT&quot;</defaultValue>
        <label>User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>System Logger Setting</label>
    <pluralLabel>System Logger Settings</pluralLabel>
</CustomObject>

src/classes/SystemLoggerTest.cls
@IsTest
private class SystemLoggerTest {
    //========================================================================================
    // Method: testLogFromApex()
    @isTest static void testLogFromApex()
    {
        Contact testContact = new Contact(FirstName='Test',LastName='Test',Email='testing@here.now');
        insert testContact;
        system.assertNotEquals(testContact.Id,null);
        String testMsg = 'Test Error: Error';
        String testId = testContact.Id;

        System_Logger_Setting__mdt setting = [SELECT Id,DeveloperName,User_Name__c,On_Debug__c,On_Error__c,On_Info__c,On_Warn__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c = :SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME
        LIMIT 1];
        Integer expectedLogCount = 0;
        expectedLogCount += (setting.On_Error__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Warn__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Info__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Debug__c == 'System Log') ? 1 : 0;

        Test.startTest();
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - About to generate system logs! ...');
        SystemLogger.log(LoggingLevel.ERROR,testMsg,testId);
        SystemLogger.log(LoggingLevel.WARN,testMsg,testId);
        SystemLogger.log(LoggingLevel.INFO,testMsg,testId);
        SystemLogger.log(LoggingLevel.DEBUG,testMsg,testId);
        SystemLogger.log(LoggingLevel.NONE,testMsg,testId);
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - ... Done generate system logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c,Running_User__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.size(),expectedLogCount);
        system.assertEquals(sysLogRecords[0].Logged_From__c,'Apex');
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Related_Object_Id__c,testId);
    }

    //========================================================================================
    // Method: testLogWebService()
    @isTest static void testLogWebService()
    {
        String testMsg = 'Something bad happened.';
        list<String> testLogLevels = new list<String>{'Error','Warn','Info','Debug','None'};
        String testLoggedFrom = 'Script';
        Contact testContact = new Contact(FirstName='Test',LastName='Test',Email='testing@here.now');
        insert testContact;
        system.assertNotEquals(testContact.Id,null);

        System_Logger_Setting__mdt setting = [SELECT Id,DeveloperName,User_Name__c,On_Debug__c,On_Error__c,On_Info__c,On_Warn__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c = :SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME
        LIMIT 1];
        Integer expectedLogCount = 0;
        expectedLogCount += (setting.On_Error__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Warn__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Info__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Debug__c == 'System Log') ? 1 : 0;

        Test.startTest();
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - About to generate system logs! ...');
        SystemLogger.createLog(testLogLevels[0],testMsg,testContact.Id,testLoggedFrom);
        SystemLogger.createLog(testLogLevels[1],testMsg,testContact.Id,testLoggedFrom);
        SystemLogger.createLog(testLogLevels[2],testMsg,testContact.Id,testLoggedFrom);
        SystemLogger.createLog(testLogLevels[3],testMsg,testContact.Id,testLoggedFrom);
        SystemLogger.createLog(testLogLevels[4],testMsg,testContact.Id,testLoggedFrom);
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - ... Done generate system logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c,Running_User__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.size(),expectedLogCount);
        system.assertEquals(sysLogRecords[0].Logged_From__c,testLoggedFrom);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Related_Object_Id__c,testContact.Id);
    }

    //========================================================================================
    // Method: testLogInvocable()
    @isTest static void testLogInvocable()
    {
        String testMsg = 'Something bad happened.';
        list<String> testLogLevels = new list<String>{'Error','Warn','Info','Debug','None'};
        String testLoggedFrom = 'Flow';
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
                + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';
        Contact testContact = new Contact(FirstName='Test',LastName='Test',Email='testing@here.now');
        insert testContact;
        system.assertNotEquals(testContact.Id,null);

        System_Logger_Setting__mdt setting = [SELECT Id,DeveloperName,User_Name__c,On_Debug__c,On_Error__c,On_Info__c,On_Warn__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c = :SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME
        LIMIT 1];
        Integer expectedLogCount = 0;
        expectedLogCount += (setting.On_Error__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Warn__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Info__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Debug__c == 'System Log') ? 1 : 0;

        list<System_Log_Event__e> eventsToPublish = new list<System_Log_Event__e>();
        for (String logLevel : testLogLevels)
        {
            eventsToPublish.add(new System_Log_Event__e
                    (
                            Flow_Log_Event__c = true,
                            Log_Level__c = logLevel,
                            Message__c = testMsg,
                            Running_UserName__c = UserInfo.getUserName(),
                            Stack_Trace__c = testStackTrace,
                            Related_Object_Id__c = testContact.Id
                    ));
        }

        Test.startTest();
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - About to generate system logs! ...');
        SystemLogger.log(eventsToPublish);
        system.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - ... Done generate system logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c,Running_User__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.size(),expectedLogCount);
        system.assertEquals(sysLogRecords[0].Logged_From__c,testLoggedFrom);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Related_Object_Id__c,testContact.Id);
    }


}