src/objects/System_Log__c.object
<CustomObject>
    <description>System log records created from Salesforce processes.</description>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Method__c</fullName>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <description>The name of the flow from which the log event was generated.</description>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Stage__c</fullName>
        <label>Flow Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <description>The severity of the log message.</description>
        <inlineHelpText>The severity of the log message.</inlineHelpText>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warn</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logged_From__c</fullName>
        <description>What type of process logged this event?</description>
        <inlineHelpText>What type of process logged this event?</inlineHelpText>
        <label>Logged From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Pentaho</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Script</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The reported log message.</description>
        <inlineHelpText>The reported log message.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Object_Id__c</fullName>
        <description>The Id of the related Object for which the log message was generated.</description>
        <inlineHelpText>The Id of the related Object for which the log message was generated.</inlineHelpText>
        <label>Related Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_UserName__c</fullName>
        <description>The UserName (login name) of the running user when the log was generated.</description>
        <inlineHelpText>The UserName (login name) of the running user when the log was generated.</inlineHelpText>
        <label>Running UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The stack trace when the log was generated.</description>
        <inlineHelpText>The stack trace when the log was generated.</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <label>System  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <recordTypes>
        <fullName>Apex</fullName>
        <active>true</active>
        <label>Apex</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flow</fullName>
        <active>true</active>
        <label>Flow</label>
    </recordTypes>
    <recordTypes>
        <fullName>Script</fullName>
        <active>true</active>
        <label>Script</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Log_Event__e.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Log_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apex Log Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apex_Method__c</fullName>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Log_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flow Log Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Stage__c</fullName>
        <label>Flow Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Object_Id__c</fullName>
        <label>Related Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_UserName__c</fullName>
        <label>Running UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Script_Log_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Script Log Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Log Event</label>
    <pluralLabel>System Log Events</pluralLabel>
</CustomObject>

src/objects/System_Logger_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Create_Case_On__c</fullName>
        <label>Create Case On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Debug__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Debug</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                    <default>true</default>
                    <label>Debug Log</label>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Error__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Error</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Info__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Info</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Warn__c</fullName>
        <defaultValue>&quot;None&quot;</defaultValue>
        <label>On Warn</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Debug Log</fullName>
                </value>
                <value>
                    <fullName>System Log</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Email_On__c</fullName>
        <label>Send Email On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <defaultValue>&quot;DEFAULT&quot;</defaultValue>
        <label>User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>System Logger Setting</label>
    <pluralLabel>System Logger Settings</pluralLabel>
</CustomObject>

src/classes/SystemLoggerUtilsTest.cls
@IsTest
private class SystemLoggerUtilsTest {
    //========================================================================================
    // Method: testGetUserLogLevelMap()
    @isTest static void testGetUserLogLevelMap()
    {
        map<String,System_Logger_Setting__mdt> sysLogSettingsByUserName = new map<String,System_Logger_Setting__mdt>();
        System_Logger_Setting__mdt sls = [SELECT Id,DeveloperName,User_Name__c,On_Debug__c,On_Error__c,On_Info__c,On_Warn__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c = :SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME
        LIMIT 1];

        system.assertNotEquals(sysLogSettingsByUserName,null);
        String debugKey = String.valueOf(LoggingLevel.DEBUG).toLowerCase().capitalize();
        String infoKey = String.valueOf(LoggingLevel.INFO).toLowerCase().capitalize();
        String warnKey = String.valueOf(LoggingLevel.WARN).toLowerCase().capitalize();
        String errorKey = String.valueOf(LoggingLevel.ERROR).toLowerCase().capitalize();

        Test.startTest();
        map<String,String> userLogLevelMap = SystemLoggerUtils.getUserLogLevelMap();
        Test.stopTest();

        system.assertNotEquals(userLogLevelMap,null);
        system.assertEquals(userLogLevelMap.get(debugKey),sls.On_Debug__c);
        system.assertEquals(userLogLevelMap.get(infoKey),sls.On_Info__c);
        system.assertEquals(userLogLevelMap.get(warnKey),sls.On_Warn__c);
        system.assertEquals(userLogLevelMap.get(errorKey),sls.On_Error__c);
    }

    //==========================================================================
    // Method: testCreateSystemLogs()
    @isTest static void testCreateSystemLogs()
    {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test Error: Error';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.Error).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        list<System_Log_Event__e> testSystemLogEvents = new list<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
                (
                        Apex_Log_Event__c = true,
                        Apex_Class__c = testClassName,
                        Apex_Method__c = testMethodName,
                        Line_Number__c = testLineNumber,
                        Log_Level__c = testLogLevel,
                        Message__c = testMsg,
                        Running_UserName__c = testUserName,
                        Stack_Trace__c = testStackTrace
                ));

        Test.startTest();
        SystemLoggerUtils.createSystemLogs(testSystemLogEvents);
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run!
        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertNotEquals(sysLogRecords.isEmpty(),true);

        system.assertEquals(sysLogRecords[0].Logged_From__c,'Apex');
        system.assertEquals(sysLogRecords[0].Apex_Class__c,testClassName);
        system.assertEquals(sysLogRecords[0].Apex_Method__c,testMethodName);
        system.assertEquals(sysLogRecords[0].Line_Number__c,testLineNumber);
        system.assertEquals(sysLogRecords[0].Log_Level__c,testLogLevel);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Running_UserName__c,testUserName);
        system.assertEquals(sysLogRecords[0].Stack_Trace__c,testStackTrace);
    }

    //==========================================================================
    // Method: testCreateLogEvent()
    @isTest static void testCreateLogEvent()
    {
        String testLoggedFrom = '';
        String testMsg = 'Test Error: Error';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.Error).toLowerCase().capitalize();
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
                + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';
        System_Log_Event__e sysLogEvent;

        Test.startTest();

        testLoggedFrom = 'Apex';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.Error,testStackTrace,testMsg,null,testLoggedFrom);

        system.assertNotEquals(sysLogEvent,null);
        system.assertEquals(sysLogEvent.Apex_Log_Event__c,true);
        system.assertEquals(sysLogEvent.Apex_Class__c,'TestClassName2');
        system.assertEquals(sysLogEvent.Apex_Method__c,'TestClassMethod2');
        system.assertEquals(sysLogEvent.Line_Number__c,'line 42');
        system.assertEquals(sysLogEvent.Log_Level__c,testLogLevel);
        system.assertEquals(sysLogEvent.Message__c,testMsg);
        system.assertEquals(sysLogEvent.Running_UserName__c,testUserName);
        system.assertEquals(sysLogEvent.Stack_Trace__c,testStackTrace);

        testLoggedFrom = 'Script';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.Error,testStackTrace,testMsg,null,testLoggedFrom);

        system.assertNotEquals(sysLogEvent,null);
        system.assertEquals(sysLogEvent.Script_Log_Event__c,true);
        system.assertEquals(sysLogEvent.Log_Level__c,testLogLevel);
        system.assertEquals(sysLogEvent.Message__c,testMsg);
        system.assertEquals(sysLogEvent.Running_UserName__c,testUserName);
        system.assertEquals(sysLogEvent.Stack_Trace__c,testStackTrace);

        testLoggedFrom = 'Flow';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.Error,testStackTrace,testMsg,null,testLoggedFrom);

        system.assertNotEquals(sysLogEvent,null);
        system.assertEquals(sysLogEvent.Flow_Log_Event__c,true);
        system.assertEquals(sysLogEvent.Log_Level__c,testLogLevel);
        system.assertEquals(sysLogEvent.Message__c,testMsg);
        system.assertEquals(sysLogEvent.Running_UserName__c,testUserName);
        system.assertEquals(sysLogEvent.Stack_Trace__c,testStackTrace);

        Test.stopTest();
    }

    //==========================================================================
    // Method: testGetCallingTraceLine()
    @isTest static void testGetCallingTraceLine()
    {
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n';
        testStackTrace += 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String traceLine = SystemLoggerUtils.getCallingTraceLine(testStackTrace);
        Test.stopTest();

        system.assertNotEquals(traceLine,null);
        system.assertEquals(traceLine.contains('TestClassName2.TestClassMethod2'),true);
    }

    //==========================================================================
    // Method: testGetMethodName()
    @isTest static void testGetMethodName()
    {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String methodName = SystemLoggerUtils.getMethodName(testTraceLine);
        Test.stopTest();

        system.assertNotEquals(methodName,null);
        system.assertEquals(methodName,'TestClassMethod2');
    }

    //==========================================================================
    // Method: testGetLineNumberString()
    @isTest static void testGetLineNumberString()
    {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String lineNumber = SystemLoggerUtils.getLineNumberString(testTraceLine);
        Test.stopTest();

        system.assertNotEquals(lineNumber,null);
        system.assertEquals(lineNumber,'line 42');
    }

    //==========================================================================
    // Method: testGetClassName()
    @isTest static void testGetClassName()
    {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String className = SystemLoggerUtils.getClassName(testTraceLine);
        Test.stopTest();

        system.assertNotEquals(className,null);
        system.assertEquals(className,'TestClassName2');
    }

    //========================================================================================
    // Method: testAddDebugLine()
    @isTest static void testAddDebugLine()
    {
        String testTraceLine = 'Class.TestClassName.TestClassMethod: line 42, column 1';
        String testMsg = 'Test Error: Error';

        Test.startTest();
        SystemLoggerUtils.addDebugLine(LoggingLevel.DEBUG,testTraceLine,testMsg);
        Test.stopTest();
    }

    //========================================================================================
    // Method: testCreateAndPublishLogEvent()
    @isTest static void testCreateAndPublishLogEvent()
    {
        String testLoggedFrom = 'Apex';
        String testMsg = 'Test Error: Some error.';
        System.LoggingLevel testLogLevel = LoggingLevel.Error;
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
                + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        SystemLoggerUtils.createAndPublishLogEvent(testLogLevel,testStackTrace,testMsg,null,testLoggedFrom);
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.isEmpty(),false);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Logged_From__c,testLoggedFrom);
    }

    //========================================================================================
    // Method: testPublishEvent()
    @isTest static void testPublishEvent()
    {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test Error: Error';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.Error).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        list<System_Log_Event__e> testSystemLogEvents = new list<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
                (
                        Apex_Log_Event__c = true,
                        Apex_Class__c = testClassName,
                        Apex_Method__c = testMethodName,
                        Line_Number__c = testLineNumber,
                        Log_Level__c = testLogLevel,
                        Message__c = testMsg,
                        Running_UserName__c = testUserName,
                        Stack_Trace__c = testStackTrace
                ));

        Test.startTest();
        SystemLoggerUtils.publishEvents(testSystemLogEvents);
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.isEmpty(),false);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Logged_From__c,'Apex');
    }
    
    //========================================================================================
    // Method: testPublishEventAsync()
    @isTest static void testPublishEventAsync()
    {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test Error: Error';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.Error).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        list<System_Log_Event__e> testSystemLogEvents = new list<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
                (
                        Apex_Log_Event__c = true,
                        Apex_Class__c = testClassName,
                        Apex_Method__c = testMethodName,
                        Line_Number__c = testLineNumber,
                        Log_Level__c = testLogLevel,
                        Message__c = testMsg,
                        Running_UserName__c = testUserName,
                        Stack_Trace__c = testStackTrace
                ));

        Test.startTest();
        // !!! Create enough records to use up the DML limit !!!
        /*list<Lead> testLeads = new list<Lead>();
        for (Integer i=0; i < Limits.getLimitDmlRows(); i++)
        {
            testLeads.add(new Lead
                    (
                            FirstName = 'Tester'+i,
                            LastName='Testing'+i,
                            Email='me' + i + '@here.now',
                            Company ='Test Company XX',
                            Status = 'New',
                            LeadSource = 'Other',
                            Industry = 'Aerospace'
                    ));
        }
        insert testLeads; // Use up the DML limit*/
        SystemLoggerUtils.publishEvents(testSystemLogEvents); // Now try to publish
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        list<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
        FROM System_Log__c];
        system.assertNotEquals(sysLogRecords,null);
        system.assertEquals(sysLogRecords.isEmpty(),false);
        system.assertEquals(sysLogRecords[0].Message__c,testMsg);
        system.assertEquals(sysLogRecords[0].Logged_From__c,'Apex');
    }

    //========================================================================================
    // Method: testGetActionMap()
    @isTest static void testGetActionMap()
    {
        list<String> testLogLevels = new list<String>{'Error','Warn','Info','Debug'};
        set<String> userNames = new set<String>{SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME};
        System_Logger_Setting__mdt sls = [SELECT Id,DeveloperName,User_Name__c,Create_Case_On__c,Send_Email_On__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c IN :userNames
        LIMIT 1];
        String emailOnSetting = sls.Send_Email_On__c;
        Boolean emailOnDebug = (emailOnSetting == 'Debug') ? true : false;
        Boolean emailOnInfo = (emailOnSetting == 'Info' || emailOnDebug) ? true : false;
        Boolean emailOnWarn = (emailOnSetting.contains('Warn') || emailOnInfo || emailOnDebug) ? true : false;
        Boolean emailOnError = (emailOnSetting.contains('Error') || emailOnWarn || emailOnInfo || emailOnDebug) ? true : false;

        map<String,map<String,Boolean>> userName2DebugLevel2EmailCreationMap = new map<String,map<String,Boolean>>();

        Test.startTest();
        userName2DebugLevel2EmailCreationMap = SystemLoggerUtils.getActionMap(userNames,'Send_Email_On__c');
        Test.stopTest();
        system.debug('userName2DebugLevel2EmailCreationMap--->'+userName2DebugLevel2EmailCreationMap);
        system.assertNotEquals(userName2DebugLevel2EmailCreationMap,null);
        system.assertEquals(userName2DebugLevel2EmailCreationMap.isEmpty(),false);
        system.assertEquals(userName2DebugLevel2EmailCreationMap.get(SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME).get('Debug'),emailOnDebug);
        system.assertEquals(userName2DebugLevel2EmailCreationMap.get(SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME).get('Info'),emailOnInfo);
        system.assertEquals(userName2DebugLevel2EmailCreationMap.get(SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME).get('Warn'),emailOnWarn);
        system.assertEquals(userName2DebugLevel2EmailCreationMap.get(SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME).get('Error'),emailOnError);
    }
}